# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events.
on: [push, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test in all modes on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
            - Game
          unityVersion:
            - 2020.1.2f1
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.1
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          artifactsPath: artifacts
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}

      # Upload test results
      - uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
